import crypto from 'node:crypto';
const ISO=new Set(['ja','en','zh','ko','vi','id','km','th','my','ne','hi','bn','ur','tl','ms','ru','uk','de','fr','es','pt','it','tr','ar','fa','sw','af','mn','ta','te','mr']);
async function body(req){if(req.body&&typeof req.body==='object')return req.body;if(typeof req.body==='string'&&req.body.trim())return JSON.parse(req.body);return await new Promise((ok,no)=>{let d='';req.setEncoding('utf8');req.on('data',c=>d+=c);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}});req.on('error',no)})}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).send('Method Not Allowed');if(!process.env.OPENAI_API_KEY)return res.status(500).send('OPENAI_API_KEY is not configured');try{const p=await body(req),sdp=String(p.sdp||'');if(!sdp.trim())return res.status(400).send('SDP is required');const id=String(p.consultationId||'').slice(0,80),ln=String(p.languageName||'自動判定').slice(0,120),lc=ISO.has(String(p.languageCode||'').toLowerCase())?String(p.languageCode).toLowerCase():'',cat=String(p.category||'相談').slice(0,120),mode=p.identityMode==='named'?'named':'anonymous',name=mode==='named'?String(p.employeeName||'').slice(0,100):'',aff=String(p.affiliation||'').slice(0,160),memo=String(p.initialNote||'').slice(0,1800);const li=lc?'相談者が選択した言語は「'+ln+'」です。原則その言語で会話し、本人が別言語へ切り替えたら合わせてください。':'相談者が希望する言語は「'+ln+'」です。最初の発話から実際の言語を判断し、その言語で会話を続けてください。';const instructions=`あなたは株式会社Rac solutionが運用するAI社内相談窓口の聞き取り担当です。
相談ID: ${id}\n分類: ${cat}\n相談方法: ${mode==='anonymous'?'匿名。氏名を聞かない。':'記名。氏名は「'+name+'」。'}\n所属: ${aff||'未入力'}\n事前メモ: ${memo||'なし'}\n${li}
目的は、会社の相談担当者が初動判断できるよう、相談者の申告、本人への影響、希望対応、共有範囲を中立に確認することです。
一度に質問は必ず1つ。原則6〜10問程度。既に答えたことを繰り返さない。本人が終了を希望したら終える。
「客観的に確認済みの事実」と「本人がそう述べている内容」を混同しない。パワハラ、違法、犯罪、懲戒対象などと断定しない。法的判断、医療診断、懲戒判断をしない。声質、アクセント、流暢さから信用性や性格を評価しない。不要なセンシティブ情報を聞かない。
人間関係やハラスメントは、具体的行動・発言、時期、頻度、同席者、記録の有無を責めずに確認する。給与・残業・休日は必要な金額・時間・日付を確認する。安全問題は現在も危険が続いているかを優先する。
生命・身体に差し迫った危険、暴力、重大事故、自傷他害の差し迫りがある場合は長い聞き取りをせず、安全な場所への移動と地域の緊急窓口・会社の安全担当・信頼できる人への連絡を優先するよう伝える。
終了前に、相談者の言語で理解した内容を短く要約して訂正点を確認し、会社に希望する対応と、誰まで内容を共有してよいか・共有してほしくない相手がいるかを1つずつ確認する。匿名の場合は氏名共有を聞かない。
開始時は短く挨拶し「今日はどのようなことで相談したいですか」に相当する質問を1つだけする。`;
const tr={model:'gpt-live-transcribe',delay:'low',prompt:'Workplace employee consultation. Topics may include relationships, harassment, pay, overtime, leave, duties, safety, resignation or suggestions. Preferred language: '+ln};if(lc)tr.language=lc;const session=JSON.stringify({type:'realtime',model:'gpt-realtime-2.1',output_modalities:['audio'],instructions,audio:{input:{transcription:tr,turn_detection:{type:'semantic_vad',eagerness:'low',create_response:true,interrupt_response:true},noise_reduction:{type:'near_field'}},output:{voice:'marin'}}});const fd=new FormData();fd.set('sdp',sdp);fd.set('session',session);const sid=crypto.createHash('sha256').update('counsel:'+(id||'anon')).digest('hex');const r=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',headers:{Authorization:'Bearer '+process.env.OPENAI_API_KEY,'OpenAI-Safety-Identifier':sid},body:fd});const text=await r.text();if(!r.ok)return res.status(r.status).send(text);res.setHeader('Content-Type','application/sdp');return res.status(200).send(text)}catch(e){console.error(e);return res.status(500).send('Failed to create consultation session')}}
